# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/v1/rag.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'api/v1/rag.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61pi/v1/rag.proto\x12\x06rag.v1\"B\n\x0cQueryRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\r\n\x05top_k\x18\x02 \x01(\x05\x12\x14\n\x0cuse_reranker\x18\x03 \x01(\x08\"\xa3\x01\n\rDocumentChunk\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\r\n\x05score\x18\x03 \x01(\x02\x12\x35\n\x08metadata\x18\x04 \x03(\x0b\x32#.rag.v1.DocumentChunk.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"a\n\rQueryResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\x12&\n\x07sources\x18\x02 \x03(\x0b\x32\x15.rag.v1.DocumentChunk\x12\x18\n\x10\x63onfidence_score\x18\x03 \x01(\x02\"Z\n\x13StreamQueryResponse\x12\x0f\n\x05\x64\x65lta\x18\x01 \x01(\tH\x00\x12\'\n\x06source\x18\x02 \x01(\x0b\x32\x15.rag.v1.DocumentChunkH\x00\x42\t\n\x07payload\"\xac\x01\n\rIngestRequest\x12\x13\n\x0b\x64ocument_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x35\n\x08metadata\x18\x04 \x03(\x0b\x32#.rag.v1.IngestRequest.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"N\n\x0eIngestResponse\x12\x13\n\x0b\x64ocument_id\x18\x01 \x01(\t\x12\x16\n\x0e\x63hunks_created\x18\x02 \x01(\x05\x12\x0f\n\x07success\x18\x03 \x01(\x08\x32\xc7\x01\n\nRagService\x12\x34\n\x05Query\x12\x14.rag.v1.QueryRequest\x1a\x15.rag.v1.QueryResponse\x12\x42\n\x0bStreamQuery\x12\x14.rag.v1.QueryRequest\x1a\x1b.rag.v1.StreamQueryResponse0\x01\x12?\n\x0eIngestDocument\x12\x15.rag.v1.IngestRequest\x1a\x16.rag.v1.IngestResponseB9Z7github.com/AnatarX/ragna/gateway-go/pkg/pb/rag/v1;ragv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.v1.rag_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z7github.com/AnatarX/ragna/gateway-go/pkg/pb/rag/v1;ragv1'
  _globals['_DOCUMENTCHUNK_METADATAENTRY']._loaded_options = None
  _globals['_DOCUMENTCHUNK_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_INGESTREQUEST_METADATAENTRY']._loaded_options = None
  _globals['_INGESTREQUEST_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_QUERYREQUEST']._serialized_start=28
  _globals['_QUERYREQUEST']._serialized_end=94
  _globals['_DOCUMENTCHUNK']._serialized_start=97
  _globals['_DOCUMENTCHUNK']._serialized_end=260
  _globals['_DOCUMENTCHUNK_METADATAENTRY']._serialized_start=213
  _globals['_DOCUMENTCHUNK_METADATAENTRY']._serialized_end=260
  _globals['_QUERYRESPONSE']._serialized_start=262
  _globals['_QUERYRESPONSE']._serialized_end=359
  _globals['_STREAMQUERYRESPONSE']._serialized_start=361
  _globals['_STREAMQUERYRESPONSE']._serialized_end=451
  _globals['_INGESTREQUEST']._serialized_start=454
  _globals['_INGESTREQUEST']._serialized_end=626
  _globals['_INGESTREQUEST_METADATAENTRY']._serialized_start=213
  _globals['_INGESTREQUEST_METADATAENTRY']._serialized_end=260
  _globals['_INGESTRESPONSE']._serialized_start=628
  _globals['_INGESTRESPONSE']._serialized_end=706
  _globals['_RAGSERVICE']._serialized_start=709
  _globals['_RAGSERVICE']._serialized_end=908
# @@protoc_insertion_point(module_scope)
