# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from api.v1 import rag_pb2 as api_dot_v1_dot_rag__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in api/v1/rag_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RagServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Query = channel.unary_unary(
                '/rag.v1.RagService/Query',
                request_serializer=api_dot_v1_dot_rag__pb2.QueryRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_rag__pb2.QueryResponse.FromString,
                _registered_method=True)
        self.StreamQuery = channel.unary_stream(
                '/rag.v1.RagService/StreamQuery',
                request_serializer=api_dot_v1_dot_rag__pb2.QueryRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_rag__pb2.StreamQueryResponse.FromString,
                _registered_method=True)
        self.IngestDocument = channel.unary_unary(
                '/rag.v1.RagService/IngestDocument',
                request_serializer=api_dot_v1_dot_rag__pb2.IngestRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_rag__pb2.IngestResponse.FromString,
                _registered_method=True)


class RagServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Query(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IngestDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RagServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Query': grpc.unary_unary_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=api_dot_v1_dot_rag__pb2.QueryRequest.FromString,
                    response_serializer=api_dot_v1_dot_rag__pb2.QueryResponse.SerializeToString,
            ),
            'StreamQuery': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamQuery,
                    request_deserializer=api_dot_v1_dot_rag__pb2.QueryRequest.FromString,
                    response_serializer=api_dot_v1_dot_rag__pb2.StreamQueryResponse.SerializeToString,
            ),
            'IngestDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestDocument,
                    request_deserializer=api_dot_v1_dot_rag__pb2.IngestRequest.FromString,
                    response_serializer=api_dot_v1_dot_rag__pb2.IngestResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rag.v1.RagService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rag.v1.RagService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RagService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.v1.RagService/Query',
            api_dot_v1_dot_rag__pb2.QueryRequest.SerializeToString,
            api_dot_v1_dot_rag__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/rag.v1.RagService/StreamQuery',
            api_dot_v1_dot_rag__pb2.QueryRequest.SerializeToString,
            api_dot_v1_dot_rag__pb2.StreamQueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IngestDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.v1.RagService/IngestDocument',
            api_dot_v1_dot_rag__pb2.IngestRequest.SerializeToString,
            api_dot_v1_dot_rag__pb2.IngestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
