// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/v1/rag.proto

package ragv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	TopK          int32                  `protobuf:"varint,2,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	UseReranker   bool                   `protobuf:"varint,3,opt,name=use_reranker,json=useReranker,proto3" json:"use_reranker,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_api_v1_rag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_rag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_rag_proto_rawDescGZIP(), []int{0}
}

func (x *QueryRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *QueryRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *QueryRequest) GetUseReranker() bool {
	if x != nil {
		return x.UseReranker
	}
	return false
}

type DocumentChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Score         float32                `protobuf:"fixed32,3,opt,name=score,proto3" json:"score,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentChunk) Reset() {
	*x = DocumentChunk{}
	mi := &file_api_v1_rag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentChunk) ProtoMessage() {}

func (x *DocumentChunk) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_rag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentChunk.ProtoReflect.Descriptor instead.
func (*DocumentChunk) Descriptor() ([]byte, []int) {
	return file_api_v1_rag_proto_rawDescGZIP(), []int{1}
}

func (x *DocumentChunk) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DocumentChunk) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *DocumentChunk) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *DocumentChunk) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type QueryResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Answer          string                 `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
	Sources         []*DocumentChunk       `protobuf:"bytes,2,rep,name=sources,proto3" json:"sources,omitempty"`
	ConfidenceScore float32                `protobuf:"fixed32,3,opt,name=confidence_score,json=confidenceScore,proto3" json:"confidence_score,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_api_v1_rag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_rag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_rag_proto_rawDescGZIP(), []int{2}
}

func (x *QueryResponse) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *QueryResponse) GetSources() []*DocumentChunk {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *QueryResponse) GetConfidenceScore() float32 {
	if x != nil {
		return x.ConfidenceScore
	}
	return 0
}

type StreamQueryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*StreamQueryResponse_Delta
	//	*StreamQueryResponse_Source
	Payload       isStreamQueryResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamQueryResponse) Reset() {
	*x = StreamQueryResponse{}
	mi := &file_api_v1_rag_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamQueryResponse) ProtoMessage() {}

func (x *StreamQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_rag_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamQueryResponse.ProtoReflect.Descriptor instead.
func (*StreamQueryResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_rag_proto_rawDescGZIP(), []int{3}
}

func (x *StreamQueryResponse) GetPayload() isStreamQueryResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *StreamQueryResponse) GetDelta() string {
	if x != nil {
		if x, ok := x.Payload.(*StreamQueryResponse_Delta); ok {
			return x.Delta
		}
	}
	return ""
}

func (x *StreamQueryResponse) GetSource() *DocumentChunk {
	if x != nil {
		if x, ok := x.Payload.(*StreamQueryResponse_Source); ok {
			return x.Source
		}
	}
	return nil
}

type isStreamQueryResponse_Payload interface {
	isStreamQueryResponse_Payload()
}

type StreamQueryResponse_Delta struct {
	Delta string `protobuf:"bytes,1,opt,name=delta,proto3,oneof"`
}

type StreamQueryResponse_Source struct {
	Source *DocumentChunk `protobuf:"bytes,2,opt,name=source,proto3,oneof"`
}

func (*StreamQueryResponse_Delta) isStreamQueryResponse_Payload() {}

func (*StreamQueryResponse_Source) isStreamQueryResponse_Payload() {}

type IngestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestRequest) Reset() {
	*x = IngestRequest{}
	mi := &file_api_v1_rag_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestRequest) ProtoMessage() {}

func (x *IngestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_rag_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestRequest.ProtoReflect.Descriptor instead.
func (*IngestRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_rag_proto_rawDescGZIP(), []int{4}
}

func (x *IngestRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *IngestRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *IngestRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *IngestRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type IngestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	ChunksCreated int32                  `protobuf:"varint,2,opt,name=chunks_created,json=chunksCreated,proto3" json:"chunks_created,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestResponse) Reset() {
	*x = IngestResponse{}
	mi := &file_api_v1_rag_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestResponse) ProtoMessage() {}

func (x *IngestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_rag_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestResponse.ProtoReflect.Descriptor instead.
func (*IngestResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_rag_proto_rawDescGZIP(), []int{5}
}

func (x *IngestResponse) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *IngestResponse) GetChunksCreated() int32 {
	if x != nil {
		return x.ChunksCreated
	}
	return 0
}

func (x *IngestResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_api_v1_rag_proto protoreflect.FileDescriptor

const file_api_v1_rag_proto_rawDesc = "" +
	"\n" +
	"\x10api/v1/rag.proto\x12\x06rag.v1\"\\\n" +
	"\fQueryRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x13\n" +
	"\x05top_k\x18\x02 \x01(\x05R\x04topK\x12!\n" +
	"\fuse_reranker\x18\x03 \x01(\bR\vuseReranker\"\xcd\x01\n" +
	"\rDocumentChunk\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x02R\x05score\x12?\n" +
	"\bmetadata\x18\x04 \x03(\v2#.rag.v1.DocumentChunk.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x83\x01\n" +
	"\rQueryResponse\x12\x16\n" +
	"\x06answer\x18\x01 \x01(\tR\x06answer\x12/\n" +
	"\asources\x18\x02 \x03(\v2\x15.rag.v1.DocumentChunkR\asources\x12)\n" +
	"\x10confidence_score\x18\x03 \x01(\x02R\x0fconfidenceScore\"i\n" +
	"\x13StreamQueryResponse\x12\x16\n" +
	"\x05delta\x18\x01 \x01(\tH\x00R\x05delta\x12/\n" +
	"\x06source\x18\x02 \x01(\v2\x15.rag.v1.DocumentChunkH\x00R\x06sourceB\t\n" +
	"\apayload\"\xde\x01\n" +
	"\rIngestRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12?\n" +
	"\bmetadata\x18\x04 \x03(\v2#.rag.v1.IngestRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"r\n" +
	"\x0eIngestResponse\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12%\n" +
	"\x0echunks_created\x18\x02 \x01(\x05R\rchunksCreated\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess2\xc7\x01\n" +
	"\n" +
	"RagService\x124\n" +
	"\x05Query\x12\x14.rag.v1.QueryRequest\x1a\x15.rag.v1.QueryResponse\x12B\n" +
	"\vStreamQuery\x12\x14.rag.v1.QueryRequest\x1a\x1b.rag.v1.StreamQueryResponse0\x01\x12?\n" +
	"\x0eIngestDocument\x12\x15.rag.v1.IngestRequest\x1a\x16.rag.v1.IngestResponseB9Z7github.com/AnatarX/ragna/gateway-go/pkg/pb/rag/v1;ragv1b\x06proto3"

var (
	file_api_v1_rag_proto_rawDescOnce sync.Once
	file_api_v1_rag_proto_rawDescData []byte
)

func file_api_v1_rag_proto_rawDescGZIP() []byte {
	file_api_v1_rag_proto_rawDescOnce.Do(func() {
		file_api_v1_rag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_rag_proto_rawDesc), len(file_api_v1_rag_proto_rawDesc)))
	})
	return file_api_v1_rag_proto_rawDescData
}

var file_api_v1_rag_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_v1_rag_proto_goTypes = []any{
	(*QueryRequest)(nil),        // 0: rag.v1.QueryRequest
	(*DocumentChunk)(nil),       // 1: rag.v1.DocumentChunk
	(*QueryResponse)(nil),       // 2: rag.v1.QueryResponse
	(*StreamQueryResponse)(nil), // 3: rag.v1.StreamQueryResponse
	(*IngestRequest)(nil),       // 4: rag.v1.IngestRequest
	(*IngestResponse)(nil),      // 5: rag.v1.IngestResponse
	nil,                         // 6: rag.v1.DocumentChunk.MetadataEntry
	nil,                         // 7: rag.v1.IngestRequest.MetadataEntry
}
var file_api_v1_rag_proto_depIdxs = []int32{
	6, // 0: rag.v1.DocumentChunk.metadata:type_name -> rag.v1.DocumentChunk.MetadataEntry
	1, // 1: rag.v1.QueryResponse.sources:type_name -> rag.v1.DocumentChunk
	1, // 2: rag.v1.StreamQueryResponse.source:type_name -> rag.v1.DocumentChunk
	7, // 3: rag.v1.IngestRequest.metadata:type_name -> rag.v1.IngestRequest.MetadataEntry
	0, // 4: rag.v1.RagService.Query:input_type -> rag.v1.QueryRequest
	0, // 5: rag.v1.RagService.StreamQuery:input_type -> rag.v1.QueryRequest
	4, // 6: rag.v1.RagService.IngestDocument:input_type -> rag.v1.IngestRequest
	2, // 7: rag.v1.RagService.Query:output_type -> rag.v1.QueryResponse
	3, // 8: rag.v1.RagService.StreamQuery:output_type -> rag.v1.StreamQueryResponse
	5, // 9: rag.v1.RagService.IngestDocument:output_type -> rag.v1.IngestResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_v1_rag_proto_init() }
func file_api_v1_rag_proto_init() {
	if File_api_v1_rag_proto != nil {
		return
	}
	file_api_v1_rag_proto_msgTypes[3].OneofWrappers = []any{
		(*StreamQueryResponse_Delta)(nil),
		(*StreamQueryResponse_Source)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_rag_proto_rawDesc), len(file_api_v1_rag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_rag_proto_goTypes,
		DependencyIndexes: file_api_v1_rag_proto_depIdxs,
		MessageInfos:      file_api_v1_rag_proto_msgTypes,
	}.Build()
	File_api_v1_rag_proto = out.File
	file_api_v1_rag_proto_goTypes = nil
	file_api_v1_rag_proto_depIdxs = nil
}
